apiVersion: apps/v1beta2
  kind: Deployment
  metadata:
    labels:
      app: monster-ui
    name: monster-ui-deployment
    namespace: ingress-nginx
  spec:
    replicas: 4
    selector:
      matchLabels:
        app: monster-ui
    template:
      metadata:
        labels:
          app: monster-ui
      spec:
        containers:
          - image: nadpereira/relautimages
            name: monster-ui
            ports:
              - containerPort: 4000

