apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: monster-ui
    name: monster-ui-deployment
    namespace: ingress-nginx
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: monster-ui
    template:
      metadata:
        labels:
          app: monster-ui
      spec:
        containers:
          - image: index.docker.io/nadpereira/relautimages
            name: monster-ui
            ports:
              - containerPort: 4000

