apiVersion: apps/v1
kind: Deployment
metadata:
    name: monster-ui-deployment
    labels:
        app: monster-ui
    namespace: ingress-nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            app: monster-ui
    template:
        metadata:
            labels: {app: monster-ui}
        spec:
            containers: [{name: monster-ui, image: 'index.docker.io/nadpereira/relautimages', ports: [{containerPort: 4000}]}]
