apiVersion: apps/v1
kind: Deployment
metadata:
    name: monster-ui-deployment
    labels:
        app: monster-ui
    namespace: ingress-nginx
spec:
    replicas: 3
    selector:
        matchLabels:
            app: monster-ui
    template:
        metadata:
            labels: {app: monster-ui}
        spec:
            containers: [{name: monster-ui, image: 'nadpereira/relautimages:monster-ui', imagePullPolicy: Always,  ports: [{containerPort: 4000}]}]
            imagePullSecrets: [{name: myregistrykey}]


---

apiVersion: v1
kind: Service                                           
metadata:
  name: monster-ui-service                             
  labels:
    app: monster-ui-service
    version: 1.0.0.0
  namespace: ingress-nginx
spec:                                                
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4000
  type: NodePort  #creates LoadBalancer
  selector:
    app: monster-ui

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monster-ui-ingress
  namespace: ingress-nginx
spec:
  rules:
  - host: ui.resistance.mnstr.io
    http:
      paths:
      - backend:
          serviceName: monster-ui-service
          servicePort: 80